project:
  type: website
  output-dir: docs
  
website:
  title: "ronny-lopez-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About Me"
      - href: geartype_web/geartype_data.qmd
        text: "Project: Fishing Vessel Gear Data"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

